/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.deltafixes.model.impl;

import com.deltafixes.model.EmployeeHiring;
import com.deltafixes.model.EmployeeHiringModel;
import com.deltafixes.model.EmployeeHiringSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the EmployeeHiring service. Represents a row in the &quot;EMP_EmployeeHiring&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>EmployeeHiringModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EmployeeHiringImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EmployeeHiringImpl
 * @generated
 */
@JSON(strict = true)
public class EmployeeHiringModelImpl
	extends BaseModelImpl<EmployeeHiring> implements EmployeeHiringModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a employee hiring model instance should use the <code>EmployeeHiring</code> interface instead.
	 */
	public static final String TABLE_NAME = "EMP_EmployeeHiring";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"employeeHiringId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"name", Types.VARCHAR}, {"technology", Types.VARCHAR},
		{"experience", Types.VARCHAR}, {"title", Types.VARCHAR},
		{"summary", Types.VARCHAR}, {"status", Types.INTEGER},
		{"statusByUserId", Types.BIGINT}, {"statusByUserName", Types.VARCHAR},
		{"statusDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("employeeHiringId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("technology", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("experience", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("title", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("summary", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table EMP_EmployeeHiring (uuid_ VARCHAR(75) null,employeeHiringId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,name VARCHAR(75) null,technology VARCHAR(75) null,experience VARCHAR(75) null,title VARCHAR(75) null,summary VARCHAR(75) null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table EMP_EmployeeHiring";

	public static final String ORDER_BY_JPQL =
		" ORDER BY employeeHiring.employeeHiringId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY EMP_EmployeeHiring.employeeHiringId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long UUID_COLUMN_BITMASK = 4L;

	public static final long EMPLOYEEHIRINGID_COLUMN_BITMASK = 8L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static EmployeeHiring toModel(EmployeeHiringSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		EmployeeHiring model = new EmployeeHiringImpl();

		model.setUuid(soapModel.getUuid());
		model.setEmployeeHiringId(soapModel.getEmployeeHiringId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setName(soapModel.getName());
		model.setTechnology(soapModel.getTechnology());
		model.setExperience(soapModel.getExperience());
		model.setTitle(soapModel.getTitle());
		model.setSummary(soapModel.getSummary());
		model.setStatus(soapModel.getStatus());
		model.setStatusByUserId(soapModel.getStatusByUserId());
		model.setStatusByUserName(soapModel.getStatusByUserName());
		model.setStatusDate(soapModel.getStatusDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<EmployeeHiring> toModels(
		EmployeeHiringSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<EmployeeHiring> models = new ArrayList<EmployeeHiring>(
			soapModels.length);

		for (EmployeeHiringSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public EmployeeHiringModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _employeeHiringId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEmployeeHiringId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _employeeHiringId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return EmployeeHiring.class;
	}

	@Override
	public String getModelClassName() {
		return EmployeeHiring.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<EmployeeHiring, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<EmployeeHiring, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EmployeeHiring, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((EmployeeHiring)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<EmployeeHiring, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<EmployeeHiring, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(EmployeeHiring)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<EmployeeHiring, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<EmployeeHiring, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, EmployeeHiring>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			EmployeeHiring.class.getClassLoader(), EmployeeHiring.class,
			ModelWrapper.class);

		try {
			Constructor<EmployeeHiring> constructor =
				(Constructor<EmployeeHiring>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<EmployeeHiring, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<EmployeeHiring, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<EmployeeHiring, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<EmployeeHiring, Object>>();
		Map<String, BiConsumer<EmployeeHiring, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<EmployeeHiring, ?>>();

		attributeGetterFunctions.put("uuid", EmployeeHiring::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<EmployeeHiring, String>)EmployeeHiring::setUuid);
		attributeGetterFunctions.put(
			"employeeHiringId", EmployeeHiring::getEmployeeHiringId);
		attributeSetterBiConsumers.put(
			"employeeHiringId",
			(BiConsumer<EmployeeHiring, Long>)
				EmployeeHiring::setEmployeeHiringId);
		attributeGetterFunctions.put("groupId", EmployeeHiring::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<EmployeeHiring, Long>)EmployeeHiring::setGroupId);
		attributeGetterFunctions.put("companyId", EmployeeHiring::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<EmployeeHiring, Long>)EmployeeHiring::setCompanyId);
		attributeGetterFunctions.put("userId", EmployeeHiring::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<EmployeeHiring, Long>)EmployeeHiring::setUserId);
		attributeGetterFunctions.put("userName", EmployeeHiring::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<EmployeeHiring, String>)EmployeeHiring::setUserName);
		attributeGetterFunctions.put(
			"createDate", EmployeeHiring::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<EmployeeHiring, Date>)EmployeeHiring::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", EmployeeHiring::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<EmployeeHiring, Date>)EmployeeHiring::setModifiedDate);
		attributeGetterFunctions.put("name", EmployeeHiring::getName);
		attributeSetterBiConsumers.put(
			"name",
			(BiConsumer<EmployeeHiring, String>)EmployeeHiring::setName);
		attributeGetterFunctions.put(
			"technology", EmployeeHiring::getTechnology);
		attributeSetterBiConsumers.put(
			"technology",
			(BiConsumer<EmployeeHiring, String>)EmployeeHiring::setTechnology);
		attributeGetterFunctions.put(
			"experience", EmployeeHiring::getExperience);
		attributeSetterBiConsumers.put(
			"experience",
			(BiConsumer<EmployeeHiring, String>)EmployeeHiring::setExperience);
		attributeGetterFunctions.put("title", EmployeeHiring::getTitle);
		attributeSetterBiConsumers.put(
			"title",
			(BiConsumer<EmployeeHiring, String>)EmployeeHiring::setTitle);
		attributeGetterFunctions.put("summary", EmployeeHiring::getSummary);
		attributeSetterBiConsumers.put(
			"summary",
			(BiConsumer<EmployeeHiring, String>)EmployeeHiring::setSummary);
		attributeGetterFunctions.put("status", EmployeeHiring::getStatus);
		attributeSetterBiConsumers.put(
			"status",
			(BiConsumer<EmployeeHiring, Integer>)EmployeeHiring::setStatus);
		attributeGetterFunctions.put(
			"statusByUserId", EmployeeHiring::getStatusByUserId);
		attributeSetterBiConsumers.put(
			"statusByUserId",
			(BiConsumer<EmployeeHiring, Long>)
				EmployeeHiring::setStatusByUserId);
		attributeGetterFunctions.put(
			"statusByUserName", EmployeeHiring::getStatusByUserName);
		attributeSetterBiConsumers.put(
			"statusByUserName",
			(BiConsumer<EmployeeHiring, String>)
				EmployeeHiring::setStatusByUserName);
		attributeGetterFunctions.put(
			"statusDate", EmployeeHiring::getStatusDate);
		attributeSetterBiConsumers.put(
			"statusDate",
			(BiConsumer<EmployeeHiring, Date>)EmployeeHiring::setStatusDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getEmployeeHiringId() {
		return _employeeHiringId;
	}

	@Override
	public void setEmployeeHiringId(long employeeHiringId) {
		_employeeHiringId = employeeHiringId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@JSON
	@Override
	public String getTechnology() {
		if (_technology == null) {
			return "";
		}
		else {
			return _technology;
		}
	}

	@Override
	public void setTechnology(String technology) {
		_technology = technology;
	}

	@JSON
	@Override
	public String getExperience() {
		if (_experience == null) {
			return "";
		}
		else {
			return _experience;
		}
	}

	@Override
	public void setExperience(String experience) {
		_experience = experience;
	}

	@JSON
	@Override
	public String getTitle() {
		if (_title == null) {
			return "";
		}
		else {
			return _title;
		}
	}

	@Override
	public void setTitle(String title) {
		_title = title;
	}

	@JSON
	@Override
	public String getSummary() {
		if (_summary == null) {
			return "";
		}
		else {
			return _summary;
		}
	}

	@Override
	public void setSummary(String summary) {
		_summary = summary;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_status = status;
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		_statusDate = statusDate;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(EmployeeHiring.class.getName()));
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), EmployeeHiring.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public EmployeeHiring toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, EmployeeHiring>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EmployeeHiringImpl employeeHiringImpl = new EmployeeHiringImpl();

		employeeHiringImpl.setUuid(getUuid());
		employeeHiringImpl.setEmployeeHiringId(getEmployeeHiringId());
		employeeHiringImpl.setGroupId(getGroupId());
		employeeHiringImpl.setCompanyId(getCompanyId());
		employeeHiringImpl.setUserId(getUserId());
		employeeHiringImpl.setUserName(getUserName());
		employeeHiringImpl.setCreateDate(getCreateDate());
		employeeHiringImpl.setModifiedDate(getModifiedDate());
		employeeHiringImpl.setName(getName());
		employeeHiringImpl.setTechnology(getTechnology());
		employeeHiringImpl.setExperience(getExperience());
		employeeHiringImpl.setTitle(getTitle());
		employeeHiringImpl.setSummary(getSummary());
		employeeHiringImpl.setStatus(getStatus());
		employeeHiringImpl.setStatusByUserId(getStatusByUserId());
		employeeHiringImpl.setStatusByUserName(getStatusByUserName());
		employeeHiringImpl.setStatusDate(getStatusDate());

		employeeHiringImpl.resetOriginalValues();

		return employeeHiringImpl;
	}

	@Override
	public int compareTo(EmployeeHiring employeeHiring) {
		long primaryKey = employeeHiring.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof EmployeeHiring)) {
			return false;
		}

		EmployeeHiring employeeHiring = (EmployeeHiring)object;

		long primaryKey = employeeHiring.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		EmployeeHiringModelImpl employeeHiringModelImpl = this;

		employeeHiringModelImpl._originalUuid = employeeHiringModelImpl._uuid;

		employeeHiringModelImpl._originalGroupId =
			employeeHiringModelImpl._groupId;

		employeeHiringModelImpl._setOriginalGroupId = false;

		employeeHiringModelImpl._originalCompanyId =
			employeeHiringModelImpl._companyId;

		employeeHiringModelImpl._setOriginalCompanyId = false;

		employeeHiringModelImpl._setModifiedDate = false;

		employeeHiringModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<EmployeeHiring> toCacheModel() {
		EmployeeHiringCacheModel employeeHiringCacheModel =
			new EmployeeHiringCacheModel();

		employeeHiringCacheModel.uuid = getUuid();

		String uuid = employeeHiringCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			employeeHiringCacheModel.uuid = null;
		}

		employeeHiringCacheModel.employeeHiringId = getEmployeeHiringId();

		employeeHiringCacheModel.groupId = getGroupId();

		employeeHiringCacheModel.companyId = getCompanyId();

		employeeHiringCacheModel.userId = getUserId();

		employeeHiringCacheModel.userName = getUserName();

		String userName = employeeHiringCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			employeeHiringCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			employeeHiringCacheModel.createDate = createDate.getTime();
		}
		else {
			employeeHiringCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			employeeHiringCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			employeeHiringCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		employeeHiringCacheModel.name = getName();

		String name = employeeHiringCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			employeeHiringCacheModel.name = null;
		}

		employeeHiringCacheModel.technology = getTechnology();

		String technology = employeeHiringCacheModel.technology;

		if ((technology != null) && (technology.length() == 0)) {
			employeeHiringCacheModel.technology = null;
		}

		employeeHiringCacheModel.experience = getExperience();

		String experience = employeeHiringCacheModel.experience;

		if ((experience != null) && (experience.length() == 0)) {
			employeeHiringCacheModel.experience = null;
		}

		employeeHiringCacheModel.title = getTitle();

		String title = employeeHiringCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			employeeHiringCacheModel.title = null;
		}

		employeeHiringCacheModel.summary = getSummary();

		String summary = employeeHiringCacheModel.summary;

		if ((summary != null) && (summary.length() == 0)) {
			employeeHiringCacheModel.summary = null;
		}

		employeeHiringCacheModel.status = getStatus();

		employeeHiringCacheModel.statusByUserId = getStatusByUserId();

		employeeHiringCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = employeeHiringCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			employeeHiringCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			employeeHiringCacheModel.statusDate = statusDate.getTime();
		}
		else {
			employeeHiringCacheModel.statusDate = Long.MIN_VALUE;
		}

		return employeeHiringCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<EmployeeHiring, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<EmployeeHiring, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EmployeeHiring, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((EmployeeHiring)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<EmployeeHiring, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<EmployeeHiring, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EmployeeHiring, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((EmployeeHiring)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, EmployeeHiring>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private long _employeeHiringId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _name;
	private String _technology;
	private String _experience;
	private String _title;
	private String _summary;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private long _columnBitmask;
	private EmployeeHiring _escapedModel;

}