/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.deltafixes.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the EmployeeHiring service. Represents a row in the &quot;EMP_EmployeeHiring&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.deltafixes.model.impl.EmployeeHiringModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.deltafixes.model.impl.EmployeeHiringImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EmployeeHiring
 * @generated
 */
@ProviderType
public interface EmployeeHiringModel
	extends BaseModel<EmployeeHiring>, GroupedModel, ShardedModel,
			StagedAuditedModel, WorkflowedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a employee hiring model instance should use the {@link EmployeeHiring} interface instead.
	 */

	/**
	 * Returns the primary key of this employee hiring.
	 *
	 * @return the primary key of this employee hiring
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this employee hiring.
	 *
	 * @param primaryKey the primary key of this employee hiring
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this employee hiring.
	 *
	 * @return the uuid of this employee hiring
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this employee hiring.
	 *
	 * @param uuid the uuid of this employee hiring
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the employee hiring ID of this employee hiring.
	 *
	 * @return the employee hiring ID of this employee hiring
	 */
	public long getEmployeeHiringId();

	/**
	 * Sets the employee hiring ID of this employee hiring.
	 *
	 * @param employeeHiringId the employee hiring ID of this employee hiring
	 */
	public void setEmployeeHiringId(long employeeHiringId);

	/**
	 * Returns the group ID of this employee hiring.
	 *
	 * @return the group ID of this employee hiring
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this employee hiring.
	 *
	 * @param groupId the group ID of this employee hiring
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this employee hiring.
	 *
	 * @return the company ID of this employee hiring
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this employee hiring.
	 *
	 * @param companyId the company ID of this employee hiring
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this employee hiring.
	 *
	 * @return the user ID of this employee hiring
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this employee hiring.
	 *
	 * @param userId the user ID of this employee hiring
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this employee hiring.
	 *
	 * @return the user uuid of this employee hiring
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this employee hiring.
	 *
	 * @param userUuid the user uuid of this employee hiring
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this employee hiring.
	 *
	 * @return the user name of this employee hiring
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this employee hiring.
	 *
	 * @param userName the user name of this employee hiring
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this employee hiring.
	 *
	 * @return the create date of this employee hiring
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this employee hiring.
	 *
	 * @param createDate the create date of this employee hiring
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this employee hiring.
	 *
	 * @return the modified date of this employee hiring
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this employee hiring.
	 *
	 * @param modifiedDate the modified date of this employee hiring
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this employee hiring.
	 *
	 * @return the name of this employee hiring
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this employee hiring.
	 *
	 * @param name the name of this employee hiring
	 */
	public void setName(String name);

	/**
	 * Returns the technology of this employee hiring.
	 *
	 * @return the technology of this employee hiring
	 */
	@AutoEscape
	public String getTechnology();

	/**
	 * Sets the technology of this employee hiring.
	 *
	 * @param technology the technology of this employee hiring
	 */
	public void setTechnology(String technology);

	/**
	 * Returns the experience of this employee hiring.
	 *
	 * @return the experience of this employee hiring
	 */
	@AutoEscape
	public String getExperience();

	/**
	 * Sets the experience of this employee hiring.
	 *
	 * @param experience the experience of this employee hiring
	 */
	public void setExperience(String experience);

	/**
	 * Returns the title of this employee hiring.
	 *
	 * @return the title of this employee hiring
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this employee hiring.
	 *
	 * @param title the title of this employee hiring
	 */
	public void setTitle(String title);

	/**
	 * Returns the summary of this employee hiring.
	 *
	 * @return the summary of this employee hiring
	 */
	@AutoEscape
	public String getSummary();

	/**
	 * Sets the summary of this employee hiring.
	 *
	 * @param summary the summary of this employee hiring
	 */
	public void setSummary(String summary);

	/**
	 * Returns the status of this employee hiring.
	 *
	 * @return the status of this employee hiring
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this employee hiring.
	 *
	 * @param status the status of this employee hiring
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this employee hiring.
	 *
	 * @return the status by user ID of this employee hiring
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this employee hiring.
	 *
	 * @param statusByUserId the status by user ID of this employee hiring
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this employee hiring.
	 *
	 * @return the status by user uuid of this employee hiring
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this employee hiring.
	 *
	 * @param statusByUserUuid the status by user uuid of this employee hiring
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this employee hiring.
	 *
	 * @return the status by user name of this employee hiring
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this employee hiring.
	 *
	 * @param statusByUserName the status by user name of this employee hiring
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this employee hiring.
	 *
	 * @return the status date of this employee hiring
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this employee hiring.
	 *
	 * @param statusDate the status date of this employee hiring
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns <code>true</code> if this employee hiring is approved.
	 *
	 * @return <code>true</code> if this employee hiring is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this employee hiring is denied.
	 *
	 * @return <code>true</code> if this employee hiring is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this employee hiring is a draft.
	 *
	 * @return <code>true</code> if this employee hiring is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this employee hiring is expired.
	 *
	 * @return <code>true</code> if this employee hiring is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this employee hiring is inactive.
	 *
	 * @return <code>true</code> if this employee hiring is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this employee hiring is incomplete.
	 *
	 * @return <code>true</code> if this employee hiring is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this employee hiring is pending.
	 *
	 * @return <code>true</code> if this employee hiring is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this employee hiring is scheduled.
	 *
	 * @return <code>true</code> if this employee hiring is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

}